name: C++ CI Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        qt_version: ['5.15.2', '6.2.2']
        include:
        - os: windows-latest
          host: windows
          cmake_args: '-G "Visual Studio 17 2022"'
        - os: windows-latest
          qt_version: '5.15.2'
          qt_arch: win64_msvc2019_64
          qt_arch_path: msvc2019_64

    steps:
    - uses: actions/checkout@v2
      with:
        path: Arduino-Source
    - uses: actions/checkout@v2
      with:
        repository: 'PokemonAutomation/Packages'
        path: Packages
    - name: Add msbuild to PATH
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      run: |
        python3 -m pip install aqtinstall
        python3 -m aqt install-qt ${{ matrix.host }} desktop ${{ matrix.qt_version }} ${{ matrix.qt_arch }} ${{ matrix.qt_modules }}
    - name: Run cmake
      run: |
        cd Arduino-Source/SerialPrograms
        mkdir bin
        cd bin
        cmake .. -DCMAKE_PREFIX_PATH=${{ github.workspace }}/${{ matrix.qt_version }}/${{ matrix.qt_arch_path }} -DQT_MAJOR:STRING=${{ matrix.qt_version_major }} ${{ matrix.cmake_args }}
    - name: Generate binaries
      if: startsWith(matrix.os, 'windows')
      run: |
        cd Arduino-Source/SerialPrograms/bin
        MSBuild.exe ./SerialPrograms.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Generate binaries
      if: startsWith(matrix.os, 'macos')
      run: |
        cd Arduino-Source/SerialPrograms/bin
        cmake --build . -j 10
    - name: Copy resources
      if: startsWith(matrix.os, 'windows')
      run: |
        robocopy Packages/SerialPrograms/Resources          Output/Resources /s
        robocopy Packages/PABotBase/PABotBase-Switch        Output/PABotBase /s
        robocopy Arduino-Source/SerialPrograms/bin          Output/Binaries libcrypto-1_1-x64.dll libssl-1_1-x64.dll Sleepy.dll tesseractPA.dll
        robocopy Arduino-Source/SerialPrograms/bin/Release  Output/Binaries SerialPrograms.exe
        exit 0
    - uses: actions/upload-artifact@v2
      if: startsWith(matrix.os, 'windows')
      with:
        name: Serial Programs for windows (${{ matrix.qt_version }})
        path: Output
